Repository prgrms-web-devcourse-final-project/WEB3_4_Pinocchio_BE, pull requests merged in 2025-04, with the labels that each got.

#22 Feat search
  .github/workflows/gemini-code-review.yml
  src/main/java/sns/pinocchio/application/search/dto/SearchResponseDto.java
  src/main/java/sns/pinocchio/application/search/service/SearchService.java
  src/main/java/sns/pinocchio/domain/search/SearchSortType.java
  src/main/java/sns/pinocchio/domain/search/SearchType.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/SearchRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/SearchRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/presentation/search/SearchController.java
  src/test/java/sns/pinocchio/application/search/service/SearchServiceTest.java
Labels: 개발

#23 Feat chat
  frontend/src/layout/background/Header.js
  frontend/src/pages/board/MainBoardList.js
  frontend/src/pages/board/MyPage.js
  frontend/src/pages/board/MyPageTabLayout.js
  frontend/src/routes/BaseRoutes.js
  frontend/src/shared/TabLayout.js
  frontend/src/shared/TableBackGroundCard.js
  frontend/src/shared/table/FlexibleTable.js
  frontend/src/shared/table/FlexibleTable.module.scss
  frontend/src/shared/table/FlexibleTableCell.js
  frontend/src/shared/table/FlexibleTableHeader.js
  frontend/src/shared/table/SimpleTable.js
  src/main/java/sns/pinocchio/application/chat/dto/ChatResponseDto.java
  src/main/java/sns/pinocchio/application/chat/service/ChatService.java
  src/main/java/sns/pinocchio/application/notification/service/NotificationService.java
  src/main/java/sns/pinocchio/domain/chat/Chat.java
  src/main/java/sns/pinocchio/domain/chatroom/ChatRoom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/ChatRoomRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/ChatRoomRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/infrastructure/shared/swagger/ErrorExamples.java
  src/main/java/sns/pinocchio/presentation/chat/ChatController.java
  src/test/java/sns/pinocchio/application/chat/service/ChatServiceTest.java
Labels: 개발, 수정

#28 refactor : member -> user 수정
  src/main/java/sns/pinocchio/config/global/auth/jwt/MemberAuthFilter.java
  src/main/java/sns/pinocchio/presentation/member/MemberController.java
  src/test/java/sns/pinocchio/domain/auth/AuthControllerTest.java
  src/test/java/sns/pinocchio/domain/member/MemberControllerTest.java
Labels: 수정

#30 Feat infrastructure
  Dockerfile
  docker-compose.yml
  terraform/main.tf
  terraform/outputs.tf
  terraform/variables.tf
Labels: 개발

#41 Refactor chat notification search
  .github/workflows/gemini-code-review.yml
  src/main/java/sns/pinocchio/application/chat/dto/ChatResponseDto.java
  src/main/java/sns/pinocchio/application/chat/service/ChatService.java
  src/main/java/sns/pinocchio/application/notification/service/NotificationService.java
  src/main/java/sns/pinocchio/application/search/dto/SearchResponseDto.java
  src/main/java/sns/pinocchio/application/search/service/SearchService.java
  src/main/java/sns/pinocchio/config/global/auth/model/CustomUserDetails.java
  src/main/java/sns/pinocchio/config/global/querydsl/QueryDslConfig.java
  src/main/java/sns/pinocchio/domain/chat/ChatException.java
  src/main/java/sns/pinocchio/domain/member/Member.java
  src/main/java/sns/pinocchio/domain/notification/Notification.java
  src/main/java/sns/pinocchio/domain/notification/NotificationException.java
  src/main/java/sns/pinocchio/domain/search/SearchSortType.java
  src/main/java/sns/pinocchio/domain/search/SearchType.java
  src/main/java/sns/pinocchio/infrastructure/member/MemberRepository.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/SearchRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/SearchRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mysql/NotificationRepository.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mysql/SearchMemberRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mysql/SearchMemberRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/infrastructure/shared/swagger/ErrorExamples.java
  src/main/java/sns/pinocchio/presentation/chat/ChatController.java
  src/main/java/sns/pinocchio/presentation/notification/NotificationController.java
  src/main/java/sns/pinocchio/presentation/search/SearchController.java
  src/main/java/sns/pinocchio/presentation/search/exception/SearchErrorCode.java
  src/test/java/sns/pinocchio/application/chat/service/ChatServiceTest.java
  src/test/java/sns/pinocchio/application/notification/service/NotificationServiceTest.java
  src/test/java/sns/pinocchio/application/search/service/SearchServiceTest.java
Labels: 버그, 수정

#42 Dev main
  .github/workflows/gemini-code-review.yml
  src/main/java/sns/pinocchio/application/chat/dto/ChatResponseDto.java
  src/main/java/sns/pinocchio/application/chat/service/ChatService.java
  src/main/java/sns/pinocchio/application/notification/service/NotificationService.java
  src/main/java/sns/pinocchio/application/search/dto/SearchResponseDto.java
  src/main/java/sns/pinocchio/application/search/service/SearchService.java
  src/main/java/sns/pinocchio/config/global/auth/model/CustomUserDetails.java
  src/main/java/sns/pinocchio/config/global/querydsl/QueryDslConfig.java
  src/main/java/sns/pinocchio/domain/chat/ChatException.java
  src/main/java/sns/pinocchio/domain/member/Member.java
  src/main/java/sns/pinocchio/domain/notification/Notification.java
  src/main/java/sns/pinocchio/domain/notification/NotificationException.java
  src/main/java/sns/pinocchio/domain/search/SearchSortType.java
  src/main/java/sns/pinocchio/domain/search/SearchType.java
  src/main/java/sns/pinocchio/infrastructure/member/MemberRepository.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/SearchRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/SearchRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mysql/NotificationRepository.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mysql/SearchMemberRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mysql/SearchMemberRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/infrastructure/shared/swagger/ErrorExamples.java
  src/main/java/sns/pinocchio/presentation/chat/ChatController.java
  src/main/java/sns/pinocchio/presentation/member/MemberInfoFindController.java
  src/main/java/sns/pinocchio/presentation/notification/NotificationController.java
  src/main/java/sns/pinocchio/presentation/search/SearchController.java
  src/main/java/sns/pinocchio/presentation/search/exception/SearchErrorCode.java
  src/test/java/sns/pinocchio/application/chat/service/ChatServiceTest.java
  src/test/java/sns/pinocchio/application/notification/service/NotificationServiceTest.java
  src/test/java/sns/pinocchio/application/search/service/SearchServiceTest.java
Labels: 버그, 수정

#45 feat - post search
  src/main/java/sns/pinocchio/application/post/PostSearchResponse.java
  src/main/java/sns/pinocchio/application/post/PostSearchService.java
  src/main/java/sns/pinocchio/domain/post/SearchSortType.java
  src/main/java/sns/pinocchio/domain/post/SearchType.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/PostSearchRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/PostSearchRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/presentation/post/PostController.java
  src/test/java/sns/pinocchio/post/PostSearchServiceTest.java
Labels: 개발

#46 Dev main
  src/main/java/sns/pinocchio/application/post/PostSearchResponse.java
  src/main/java/sns/pinocchio/application/post/PostSearchService.java
  src/main/java/sns/pinocchio/domain/post/SearchSortType.java
  src/main/java/sns/pinocchio/domain/post/SearchType.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/PostSearchRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/PostSearchRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/presentation/post/PostController.java
  src/test/java/sns/pinocchio/post/PostSearchServiceTest.java
Labels: 개발

#50 Refactor chat notification search
  src/main/java/sns/pinocchio/application/chat/service/ChatService.java
  src/main/java/sns/pinocchio/application/post/PostSearchService.java
  src/main/java/sns/pinocchio/config/securityConfig/SecurityConfig.java
  src/main/java/sns/pinocchio/domain/post/SearchSortType.java
  src/main/java/sns/pinocchio/domain/post/SearchType.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/PostSearchRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/PostSearchRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/presentation/post/PostController.java
  src/main/java/sns/pinocchio/presentation/post/exception/PostErrorCode.java
  src/test/java/sns/pinocchio/post/PostSearchServiceTest.java
Labels: 버그, 수정

#51 Dev main
  src/main/java/sns/pinocchio/application/chat/service/ChatService.java
  src/main/java/sns/pinocchio/application/post/PostSearchService.java
  src/main/java/sns/pinocchio/config/securityConfig/SecurityConfig.java
  src/main/java/sns/pinocchio/domain/post/SearchSortType.java
  src/main/java/sns/pinocchio/domain/post/SearchType.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/PostSearchRepositoryCustom.java
  src/main/java/sns/pinocchio/infrastructure/persistence/mongodb/PostSearchRepositoryCustomImpl.java
  src/main/java/sns/pinocchio/presentation/post/PostController.java
  src/main/java/sns/pinocchio/presentation/post/exception/PostErrorCode.java
  src/test/java/sns/pinocchio/post/PostSearchServiceTest.java
Labels: 버그, 수정

#53 fix: 게시물 검색 API 응답데이터 중, query 값이 제대로 안나오는 이슈 수정
  src/main/java/sns/pinocchio/application/post/PostSearchService.java
Labels: 버그

#56 Refactor chat notification search
  src/main/java/sns/pinocchio/application/chat/service/ChatService.java
  src/main/java/sns/pinocchio/application/notification/service/NotificationService.java
  src/main/java/sns/pinocchio/application/post/PostSearchService.java
  src/main/java/sns/pinocchio/domain/chat/ChatException.java
  src/main/java/sns/pinocchio/domain/notification/NotificationException.java
  src/main/java/sns/pinocchio/infrastructure/shared/exception/BaseException.java
  src/main/java/sns/pinocchio/infrastructure/shared/exception/GlobalExceptionHandler.java
  src/main/java/sns/pinocchio/presentation/chat/exception/ChatErrorCode.java
  src/main/java/sns/pinocchio/presentation/chat/exception/ChatException.java
  src/main/java/sns/pinocchio/presentation/chat/exception/ChatExceptionHandler.java
  src/main/java/sns/pinocchio/presentation/notification/exception/NotificationErrorCode.java
  src/main/java/sns/pinocchio/presentation/notification/exception/NotificationException.java
  src/main/java/sns/pinocchio/presentation/notification/exception/NotificationExceptionHandler.java
  src/main/java/sns/pinocchio/presentation/search/exception/SearchException.java
  src/main/java/sns/pinocchio/presentation/search/exception/SearchExceptionHandler.java
  src/test/java/sns/pinocchio/application/chat/service/ChatServiceTest.java
  src/test/java/sns/pinocchio/application/notification/service/NotificationServiceTest.java
  src/test/java/sns/pinocchio/application/search/service/SearchServiceTest.java
Labels: 버그

#57 Dev main
  src/main/java/sns/pinocchio/application/chat/service/ChatService.java
  src/main/java/sns/pinocchio/application/notification/service/NotificationService.java
  src/main/java/sns/pinocchio/domain/chat/ChatException.java
  src/main/java/sns/pinocchio/domain/notification/NotificationException.java
  src/main/java/sns/pinocchio/infrastructure/shared/exception/BaseException.java
  src/main/java/sns/pinocchio/infrastructure/shared/exception/GlobalExceptionHandler.java
  src/main/java/sns/pinocchio/presentation/chat/exception/ChatErrorCode.java
  src/main/java/sns/pinocchio/presentation/chat/exception/ChatException.java
  src/main/java/sns/pinocchio/presentation/chat/exception/ChatExceptionHandler.java
  src/main/java/sns/pinocchio/presentation/notification/exception/NotificationErrorCode.java
  src/main/java/sns/pinocchio/presentation/notification/exception/NotificationException.java
  src/main/java/sns/pinocchio/presentation/notification/exception/NotificationExceptionHandler.java
  src/main/java/sns/pinocchio/presentation/search/exception/SearchException.java
  src/main/java/sns/pinocchio/presentation/search/exception/SearchExceptionHandler.java
  src/test/java/sns/pinocchio/application/chat/service/ChatServiceTest.java
  src/test/java/sns/pinocchio/application/notification/service/NotificationServiceTest.java
  src/test/java/sns/pinocchio/application/search/service/SearchServiceTest.java
Labels: 버그

#62 Feat infrastructure
  .gitignore
  terraform/main.tf
  terraform/outputs.tf
  terraform/variables.tf
Labels: 수정

#63 fix: terraform 문서 수정
  terraform/main.tf
Labels: 수정
